# Generated by Django 4.1.7 on 2023-02-27 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_code', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=200)),
                ('city_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelDataApp.city')),
            ],
        ),
    ]
